
import { GoogleGenAI, Modality } from "@google/genai";
import { ImageFile } from "../types";

export const generateImageWithPrompt = async (imageFile: ImageFile, prompt: string): Promise<string> => {
    // FIX: Per guidelines, instantiate GoogleGenAI with process.env.API_KEY directly.
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                { inlineData: { data: imageFile.base64, mimeType: imageFile.mimeType } },
                { text: prompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }
    throw new Error("No image generated by the API.");
};


export const generateVideoFromImage = async (
    imageFile: ImageFile,
    prompt: string,
    aspectRatio: '16:9' | '9:16',
    onProgress: (message: string) => void
): Promise<string> => {
    // FIX: Per guidelines, instantiate GoogleGenAI with process.env.API_KEY directly.
    const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });
    onProgress("Starting video generation...");
    let operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt,
        image: {
            imageBytes: imageFile.base64,
            mimeType: imageFile.mimeType,
        },
        config: {
            numberOfVideos: 1,
            resolution: '720p',
            aspectRatio: aspectRatio,
        }
    });

    onProgress("Operation initiated. Waiting for video to process...");
    while (!operation.done) {
        await new Promise(resolve => setTimeout(resolve, 10000)); // Poll every 10 seconds
        try {
            operation = await ai.operations.getVideosOperation({ operation: operation });
        } catch (e) {
            console.error("Error polling for video operation status:", e);
            if (e instanceof Error && e.message.includes("Requested entity was not found.")) {
                throw new Error("API key not found or invalid. Please re-select your API key.");
            }
            throw e; // Re-throw other errors
        }
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) {
        throw new Error("Video generation completed, but no download link was found.");
    }
    
    onProgress("Fetching generated video...");
    // FIX: Per guidelines, use process.env.API_KEY directly.
    const videoResponse = await fetch(`${downloadLink}&key=${process.env.API_KEY!}`);
    if (!videoResponse.ok) {
        throw new Error(`Failed to download video file. Status: ${videoResponse.statusText}`);
    }
    const videoBlob = await videoResponse.blob();
    return URL.createObjectURL(videoBlob);
};
