
import { GoogleGenAI, Modality } from "@google/genai";
import { ImageFile } from "../types";

declare global {
    interface AIStudio {
        getApiKey?: () => Promise<string | undefined>;
    }
    interface Window {
        aistudio?: AIStudio;
    }
}

const getApiKey = async (providedKey?: string): Promise<string> => {
    if (providedKey) {
        return providedKey;
    }

    if (window.aistudio?.getApiKey) {
        try {
            const secretKey = await window.aistudio.getApiKey();
            if (secretKey) {
                return secretKey;
            }
        } catch (error) {
            console.warn('Failed to retrieve API key from Secrets:', error);
        }
    }

    const envKey = import.meta.env.VITE_GEMINI_API_KEY;
    if (envKey && envKey !== 'your_gemini_api_key_here') {
        return envKey;
    }

    throw new Error("Gemini API key is required. Please select an API key from the Secrets section or set VITE_GEMINI_API_KEY.");
};

export const generateImageWithPrompt = async (imageFile: ImageFile, prompt: string, apiKey?: string): Promise<string> => {
    const key = await getApiKey(apiKey);
    const ai = new GoogleGenAI({ apiKey: key });
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                { inlineData: { data: imageFile.base64, mimeType: imageFile.mimeType } },
                { text: prompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return part.inlineData.data;
        }
    }
    throw new Error("No image generated by the API.");
};


export const generateVideoFromImage = async (
    imageFile: ImageFile,
    prompt: string,
    aspectRatio: '16:9' | '9:16',
    onProgress: (message: string) => void,
    apiKey?: string
): Promise<string> => {
    const key = await getApiKey(apiKey);
    const ai = new GoogleGenAI({ apiKey: key });
    onProgress("Starting video generation...");
    let operation = await ai.models.generateVideos({
        model: 'veo-3.1-fast-generate-preview',
        prompt,
        image: {
            imageBytes: imageFile.base64,
            mimeType: imageFile.mimeType,
        },
        config: {
            numberOfVideos: 1,
            resolution: '720p',
            aspectRatio: aspectRatio,
        }
    });

    onProgress("Operation initiated. Waiting for video to process...");
    while (!operation.done) {
        await new Promise(resolve => setTimeout(resolve, 10000)); // Poll every 10 seconds
        try {
            operation = await ai.operations.getVideosOperation({ operation: operation });
        } catch (e) {
            console.error("Error polling for video operation status:", e);
            if (e instanceof Error && e.message.includes("Requested entity was not found.")) {
                throw new Error("API key not found or invalid. Please re-select your API key.");
            }
            throw e; // Re-throw other errors
        }
    }

    const downloadLink = operation.response?.generatedVideos?.[0]?.video?.uri;
    if (!downloadLink) {
        throw new Error("Video generation completed, but no download link was found.");
    }
    
    onProgress("Fetching generated video...");
    const videoResponse = await fetch(`${downloadLink}&key=${key}`);
    if (!videoResponse.ok) {
        throw new Error(`Failed to download video file. Status: ${videoResponse.statusText}`);
    }
    const videoBlob = await videoResponse.blob();
    return URL.createObjectURL(videoBlob);
};
